# Generator
BIN_FILE = 'generator.bin'
AUTHOR_SIGN = "kikediebot"

# Twitter
CONSUMER_KEY = "{TWITTER_CONSUMER_KEY}"
CONSUMER_SECRET = "{TWITTER_CONSUMER_SECRET}"
ACCESS_TOKEN = "{TWITTER_ACCESS_TOKEN}"
ACCESS_TOKEN_SECRET = "{TWITTER_ACCESS_TOKEN_SECRET}"

# Parser
DOMAIN = "http://{DOMAIN_HERE}/page/{n}/?s=carta"
USER_AGENT = "{USER_AGENT}"
PAGES_LIMIT = 20
